[SC-890] Feature/get rid of truffle
1inch/merkle-distribution pull request #20
Opened 2023-08-17 07:06 UTC by SevenSwen

2023-08-18 18:27 UTC, ZumZoom requested changes

2023-08-18 18:27 UTC, ZumZoom commented on hardhat.config.js
> +require('@nomiclabs/hardhat-etherscan');
?

2023-08-18 18:27 UTC, ZumZoom commented on package.json
> +    "@nomiclabs/hardhat-etherscan": "3.1.7",
?

2023-08-18 18:27 UTC, ZumZoom commented on contracts/CumulativeMerkleDrop.sol
> +    error MerkleRootWasUpdated();
move errors to interface

2023-08-18 18:27 UTC, ZumZoom commented on contracts/CumulativeMerkleDrop128.sol
> +    error MerkleRootWasUpdated();
move errors to interface

2023-08-18 18:27 UTC, ZumZoom commented on contracts/SignatureMerkleDrop128.sol
> +    error DropAlreadyClaimed();
move errors to interface

2023-08-18 18:27 UTC, ZumZoom commented on test/CumulativeMerkleDrop.test.js
> +            constracts: { token, drop },
```suggestion
            contracts: { token, drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/CumulativeMerkleDrop.test.js
> +        const { accounts: { alice }, constracts: { token, drop } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { alice }, contracts: { token, drop } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/CumulativeMerkleDrop128.test.js
> +            constracts: { token, drop },
```suggestion
            contracts: { token, drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/CumulativeMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { token, drop } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { alice }, contracts: { token, drop } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/MerkleDrop.behavior.js
> +                        constracts: { drop },
```suggestion
                        contracts: { drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/MerkleDrop.behavior.js
> +                        constracts: { drop },
```suggestion
                        contracts: { drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/MerkleDrop.behavior.js
> +                constracts: { drop },
```suggestion
                contracts: { drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/CumulativeMerkleDrop.behavior.js
> +                constracts: { token, drop },
```suggestion
                contracts: { token, drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +            constracts: { token, drop },
```suggestion
            contracts: { token, drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +        const { constracts: { drop }, others: { hashedElements, leaves, proofs } } = await loadFixture(deployContractsFixture);
```suggestion
        const { contracts: { drop }, others: { hashedElements, leaves, proofs } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { alice }, contracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { drop }, others: { signature } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { alice }, contracts: { drop }, others: { signature } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { bob }, constracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { bob }, contracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```suggestion
        const { accounts: { alice }, contracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/CumulativeMerkleDrop.behavior.js
> +                constracts: { token, drop },
```suggestion
                contracts: { token, drop },
```

2023-08-18 18:27 UTC, ZumZoom commented on test/behaviors/CumulativeMerkleDrop.behavior.js
> +                constracts: { token, drop },
```suggestion
                contracts: { token, drop },
```

2023-08-21 04:52 UTC, SevenSwen commented on contracts/SignatureMerkleDrop128.sol
> +    error DropAlreadyClaimed();
fixed

2023-08-21 04:52 UTC, SevenSwen commented on contracts/CumulativeMerkleDrop.sol
> +    error MerkleRootWasUpdated();
fixed

2023-08-21 04:52 UTC, SevenSwen commented on contracts/CumulativeMerkleDrop128.sol
> +    error MerkleRootWasUpdated();
fixed

2023-08-21 04:53 UTC, SevenSwen commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { drop }, others: { signature } } = await loadFixture(deployContractsFixture);
fixed

2023-08-21 04:53 UTC, SevenSwen commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { alice }, constracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
fixed

2023-08-21 04:53 UTC, SevenSwen commented on test/behaviors/CumulativeMerkleDrop.behavior.js
> +                constracts: { token, drop },
fixed

2023-08-21 04:53 UTC, SevenSwen commented on test/behaviors/CumulativeMerkleDrop.behavior.js
> +                constracts: { token, drop },
fixed

2023-08-21 04:53 UTC, SevenSwen commented on test/SignatureMerkleDrop128.test.js
> +        const { accounts: { bob }, constracts: { drop }, others: { hashedElements, leaves, proofs, signature } } = await loadFixture(deployContractsFixture);
fixed

2023-08-21 07:29 UTC, SevenSwen commented on hardhat.config.js
> +require('@nomiclabs/hardhat-etherscan');
fixed

2023-08-21 07:31 UTC, SevenSwen commented on package.json
> +    "@nomiclabs/hardhat-etherscan": "3.1.7",
fixed

2023-08-21 08:55 UTC, merged